path: ./cvat #dataset root directory
train: images/train #train images (relative to 'path')
val: images/train #val images (relative to 'path')

#Classes
names:
  0: mainpage_username_textfield
  1: mainpage_login_button
  2: security_word
  3: security_image
  4: security_confirm_button
  5: security_question
  6: login_details
  7: password_please
  8: password_textfield
  9: password_login_button
  10: password_login_button_disabled
